/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIRecommendation {
  'id' : bigint,
  'applied' : boolean,
  'estimatedSavings' : number,
  'message' : string,
  'priority' : bigint,
}
export interface AnomalyLog {
  'anomalyType' : string,
  'severityScore' : bigint,
  'device' : string,
  'timestamp' : Time,
}
export interface CarbonEmissionCalculation {
  'emissionFactor' : number,
  'co2Kg' : number,
  'energyKWh' : number,
  'timestamp' : Time,
}
export interface CarbonFootprint { 'timestamp' : Time, 'reductionKg' : number }
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface CostSaving { 'timestamp' : Time, 'amount' : number }
export interface DeviceEfficiency {
  'efficiencyScore' : number,
  'deviceId' : string,
}
export interface DeviceStatus {
  'status' : string,
  'deviceId' : string,
  'deviceType' : string,
  'healthScore' : bigint,
  'location' : string,
}
export interface EnergyReading {
  'kWh' : number,
  'device' : string,
  'timestamp' : Time,
  'location' : string,
}
export interface NetZeroProgress {
  'currentEmissions' : number,
  'progressPercentage' : number,
  'targetEmissions' : number,
}
export interface ROICalculation {
  'monthlySavings' : number,
  'investmentAmount' : number,
  'timestamp' : Time,
  'roiMonths' : number,
}
export interface SmartAlert {
  'id' : bigint,
  'alertType' : string,
  'acknowledged' : boolean,
  'message' : string,
  'timestamp' : Time,
  'severity' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<[bigint], undefined>,
  'addDeviceEfficiency' : ActorMethod<[DeviceEfficiency], undefined>,
  'addRecommendation' : ActorMethod<[AIRecommendation], undefined>,
  'createAlert' : ActorMethod<[SmartAlert], undefined>,
  'getEnergyReadingsByDevice' : ActorMethod<[string], Array<EnergyReading>>,
  'getNetZeroProgress' : ActorMethod<[], [] | [NetZeroProgress]>,
  'getTopEfficientDevices' : ActorMethod<[bigint], Array<DeviceEfficiency>>,
  'logAnomaly' : ActorMethod<[AnomalyLog], undefined>,
  'registerDevice' : ActorMethod<[DeviceStatus], undefined>,
  'storeCarbonCalculation' : ActorMethod<
    [CarbonEmissionCalculation],
    undefined
  >,
  'storeCarbonFootprint' : ActorMethod<[CarbonFootprint], undefined>,
  'storeCostSaving' : ActorMethod<[CostSaving], undefined>,
  'storeEnergyReading' : ActorMethod<[EnergyReading], undefined>,
  'storeROICalculation' : ActorMethod<[ROICalculation], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'updateNetZeroProgress' : ActorMethod<[NetZeroProgress], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];