/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceEfficiency = IDL.Record({
  'efficiencyScore' : IDL.Float64,
  'deviceId' : IDL.Text,
});
export const AIRecommendation = IDL.Record({
  'id' : IDL.Nat,
  'applied' : IDL.Bool,
  'estimatedSavings' : IDL.Float64,
  'message' : IDL.Text,
  'priority' : IDL.Nat,
});
export const Time = IDL.Int;
export const SmartAlert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
  'severity' : IDL.Nat,
});
export const EnergyReading = IDL.Record({
  'kWh' : IDL.Float64,
  'device' : IDL.Text,
  'timestamp' : Time,
  'location' : IDL.Text,
});
export const NetZeroProgress = IDL.Record({
  'currentEmissions' : IDL.Float64,
  'progressPercentage' : IDL.Float64,
  'targetEmissions' : IDL.Float64,
});
export const AnomalyLog = IDL.Record({
  'anomalyType' : IDL.Text,
  'severityScore' : IDL.Nat,
  'device' : IDL.Text,
  'timestamp' : Time,
});
export const DeviceStatus = IDL.Record({
  'status' : IDL.Text,
  'deviceId' : IDL.Text,
  'deviceType' : IDL.Text,
  'healthScore' : IDL.Nat,
  'location' : IDL.Text,
});
export const CarbonEmissionCalculation = IDL.Record({
  'emissionFactor' : IDL.Float64,
  'co2Kg' : IDL.Float64,
  'energyKWh' : IDL.Float64,
  'timestamp' : Time,
});
export const CarbonFootprint = IDL.Record({
  'timestamp' : Time,
  'reductionKg' : IDL.Float64,
});
export const CostSaving = IDL.Record({
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const ROICalculation = IDL.Record({
  'monthlySavings' : IDL.Float64,
  'investmentAmount' : IDL.Float64,
  'timestamp' : Time,
  'roiMonths' : IDL.Float64,
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
  'addDeviceEfficiency' : IDL.Func([DeviceEfficiency], [], []),
  'addRecommendation' : IDL.Func([AIRecommendation], [], []),
  'createAlert' : IDL.Func([SmartAlert], [], []),
  'getEnergyReadingsByDevice' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EnergyReading)],
      ['query'],
    ),
  'getNetZeroProgress' : IDL.Func([], [IDL.Opt(NetZeroProgress)], ['query']),
  'getTopEfficientDevices' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DeviceEfficiency)],
      ['query'],
    ),
  'logAnomaly' : IDL.Func([AnomalyLog], [], []),
  'registerDevice' : IDL.Func([DeviceStatus], [], []),
  'storeCarbonCalculation' : IDL.Func([CarbonEmissionCalculation], [], []),
  'storeCarbonFootprint' : IDL.Func([CarbonFootprint], [], []),
  'storeCostSaving' : IDL.Func([CostSaving], [], []),
  'storeEnergyReading' : IDL.Func([EnergyReading], [], []),
  'storeROICalculation' : IDL.Func([ROICalculation], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'updateNetZeroProgress' : IDL.Func([NetZeroProgress], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceEfficiency = IDL.Record({
    'efficiencyScore' : IDL.Float64,
    'deviceId' : IDL.Text,
  });
  const AIRecommendation = IDL.Record({
    'id' : IDL.Nat,
    'applied' : IDL.Bool,
    'estimatedSavings' : IDL.Float64,
    'message' : IDL.Text,
    'priority' : IDL.Nat,
  });
  const Time = IDL.Int;
  const SmartAlert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
    'severity' : IDL.Nat,
  });
  const EnergyReading = IDL.Record({
    'kWh' : IDL.Float64,
    'device' : IDL.Text,
    'timestamp' : Time,
    'location' : IDL.Text,
  });
  const NetZeroProgress = IDL.Record({
    'currentEmissions' : IDL.Float64,
    'progressPercentage' : IDL.Float64,
    'targetEmissions' : IDL.Float64,
  });
  const AnomalyLog = IDL.Record({
    'anomalyType' : IDL.Text,
    'severityScore' : IDL.Nat,
    'device' : IDL.Text,
    'timestamp' : Time,
  });
  const DeviceStatus = IDL.Record({
    'status' : IDL.Text,
    'deviceId' : IDL.Text,
    'deviceType' : IDL.Text,
    'healthScore' : IDL.Nat,
    'location' : IDL.Text,
  });
  const CarbonEmissionCalculation = IDL.Record({
    'emissionFactor' : IDL.Float64,
    'co2Kg' : IDL.Float64,
    'energyKWh' : IDL.Float64,
    'timestamp' : Time,
  });
  const CarbonFootprint = IDL.Record({
    'timestamp' : Time,
    'reductionKg' : IDL.Float64,
  });
  const CostSaving = IDL.Record({ 'timestamp' : Time, 'amount' : IDL.Float64 });
  const ROICalculation = IDL.Record({
    'monthlySavings' : IDL.Float64,
    'investmentAmount' : IDL.Float64,
    'timestamp' : Time,
    'roiMonths' : IDL.Float64,
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
    'addDeviceEfficiency' : IDL.Func([DeviceEfficiency], [], []),
    'addRecommendation' : IDL.Func([AIRecommendation], [], []),
    'createAlert' : IDL.Func([SmartAlert], [], []),
    'getEnergyReadingsByDevice' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EnergyReading)],
        ['query'],
      ),
    'getNetZeroProgress' : IDL.Func([], [IDL.Opt(NetZeroProgress)], ['query']),
    'getTopEfficientDevices' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DeviceEfficiency)],
        ['query'],
      ),
    'logAnomaly' : IDL.Func([AnomalyLog], [], []),
    'registerDevice' : IDL.Func([DeviceStatus], [], []),
    'storeCarbonCalculation' : IDL.Func([CarbonEmissionCalculation], [], []),
    'storeCarbonFootprint' : IDL.Func([CarbonFootprint], [], []),
    'storeCostSaving' : IDL.Func([CostSaving], [], []),
    'storeEnergyReading' : IDL.Func([EnergyReading], [], []),
    'storeROICalculation' : IDL.Func([ROICalculation], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'updateNetZeroProgress' : IDL.Func([NetZeroProgress], [], []),
  });
};

export const init = ({ IDL }) => { return []; };