/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EnergyReading {
    kWh: number;
    device: string;
    timestamp: Time;
    location: string;
}
export interface CarbonEmissionCalculation {
    emissionFactor: number;
    co2Kg: number;
    energyKWh: number;
    timestamp: Time;
}
export interface ContactMessage {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface SmartAlert {
    id: bigint;
    alertType: string;
    acknowledged: boolean;
    message: string;
    timestamp: Time;
    severity: bigint;
}
export type Time = bigint;
export interface NetZeroProgress {
    currentEmissions: number;
    progressPercentage: number;
    targetEmissions: number;
}
export interface CostSaving {
    timestamp: Time;
    amount: number;
}
export interface AIRecommendation {
    id: bigint;
    applied: boolean;
    estimatedSavings: number;
    message: string;
    priority: bigint;
}
export interface CarbonFootprint {
    timestamp: Time;
    reductionKg: number;
}
export interface ROICalculation {
    monthlySavings: number;
    investmentAmount: number;
    timestamp: Time;
    roiMonths: number;
}
export interface AnomalyLog {
    anomalyType: string;
    severityScore: bigint;
    device: string;
    timestamp: Time;
}
export interface DeviceEfficiency {
    efficiencyScore: number;
    deviceId: string;
}
export interface DeviceStatus {
    status: string;
    deviceId: string;
    deviceType: string;
    healthScore: bigint;
    location: string;
}
export interface backendInterface {
    acknowledgeAlert(alertId: bigint): Promise<void>;
    addDeviceEfficiency(efficiency: DeviceEfficiency): Promise<void>;
    addRecommendation(rec: AIRecommendation): Promise<void>;
    createAlert(alert: SmartAlert): Promise<void>;
    getEnergyReadingsByDevice(device: string): Promise<Array<EnergyReading>>;
    getNetZeroProgress(): Promise<NetZeroProgress | null>;
    getTopEfficientDevices(limit: bigint): Promise<Array<DeviceEfficiency>>;
    logAnomaly(anomaly: AnomalyLog): Promise<void>;
    registerDevice(device: DeviceStatus): Promise<void>;
    storeCarbonCalculation(calc: CarbonEmissionCalculation): Promise<void>;
    storeCarbonFootprint(fp: CarbonFootprint): Promise<void>;
    storeCostSaving(saving: CostSaving): Promise<void>;
    storeEnergyReading(reading: EnergyReading): Promise<void>;
    storeROICalculation(roi: ROICalculation): Promise<void>;
    submitContactMessage(msg: ContactMessage): Promise<void>;
    updateNetZeroProgress(progress: NetZeroProgress): Promise<void>;
}
import type { NetZeroProgress as _NetZeroProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async addDeviceEfficiency(arg0: DeviceEfficiency): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeviceEfficiency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeviceEfficiency(arg0);
            return result;
        }
    }
    async addRecommendation(arg0: AIRecommendation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecommendation(arg0);
            return result;
        }
    }
    async createAlert(arg0: SmartAlert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0);
            return result;
        }
    }
    async getEnergyReadingsByDevice(arg0: string): Promise<Array<EnergyReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnergyReadingsByDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnergyReadingsByDevice(arg0);
            return result;
        }
    }
    async getNetZeroProgress(): Promise<NetZeroProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetZeroProgress();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetZeroProgress();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopEfficientDevices(arg0: bigint): Promise<Array<DeviceEfficiency>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopEfficientDevices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopEfficientDevices(arg0);
            return result;
        }
    }
    async logAnomaly(arg0: AnomalyLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logAnomaly(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logAnomaly(arg0);
            return result;
        }
    }
    async registerDevice(arg0: DeviceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(arg0);
            return result;
        }
    }
    async storeCarbonCalculation(arg0: CarbonEmissionCalculation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeCarbonCalculation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeCarbonCalculation(arg0);
            return result;
        }
    }
    async storeCarbonFootprint(arg0: CarbonFootprint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeCarbonFootprint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeCarbonFootprint(arg0);
            return result;
        }
    }
    async storeCostSaving(arg0: CostSaving): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeCostSaving(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeCostSaving(arg0);
            return result;
        }
    }
    async storeEnergyReading(arg0: EnergyReading): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeEnergyReading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeEnergyReading(arg0);
            return result;
        }
    }
    async storeROICalculation(arg0: ROICalculation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeROICalculation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeROICalculation(arg0);
            return result;
        }
    }
    async submitContactMessage(arg0: ContactMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return result;
        }
    }
    async updateNetZeroProgress(arg0: NetZeroProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNetZeroProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNetZeroProgress(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NetZeroProgress]): NetZeroProgress | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
